In [5]:
import numpy as np

In [6]:
mid_scores = np.array([10, 20, 30])
final_scores = np.array([60, 70, 80])

total = mid_scores + final_scores
print(f'시험성적의 합계 : {total}')
print(f'시험성적의 평균 : {total/2}')

시험성적의 합계 : [ 70  90 110]
시험성적의 평균 : [35. 45. 55.]


In [8]:
a = np.array(range(1, 11))
b = np.array(range(10, 101, 10))

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[ 11  22  33  44  55  66  77  88  99 110]
[ -9 -18 -27 -36 -45 -54 -63 -72 -81 -90]
[  10   40   90  160  250  360  490  640  810 1000]
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]


In [4]:
a = np.array([1, 2, 3])
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.itemsize)
print(a.size)

(3,)
1
int64
8
3


In [6]:
a = np.array(range(1, 11)) + np.array(range(10, 101, 10))
print(a)
print(a.shape)
print(a.size)

[ 11  22  33  44  55  66  77  88  99 110]
(10,)
10


In [7]:
salary = np.array([220, 250, 230])
salary += 100
print(salary)

[320 350 330]


In [8]:
salary = np.array([220, 250, 230])
salary *= 2
print(salary)

[440 500 460]


In [12]:
salary = np.array([220, 250, 230])
salary = salary * 2.1
print(salary)

[462. 525. 483.]


In [14]:
lst = [100, 'test', 3.0, False]
print(lst)

tangled = np.array([100, 'test', 3.0, False])
print(tangled)

[100, 'test', 3.0, False]
['100' 'test' '3.0' 'False']


In [15]:
import time

start = time.time() # 시작 시간을 지정

# 백터화 연산 대신 반복문 이용
total = 0
for i in np.arange(100000):
    total += i
end = time.time()

print(f'total = {total}')
print('{:.5f} sec'.format(end-start))

total = 4999950000
0.01016 sec


In [16]:
start = time.time()

# 넘파이의 벡터화 연산 사용
total = np.sum(np.arange(100000))
end = time.time()

print(f'total = {total}')
print('{:.5f} sec'.format(end-start))

total = 4999950000
0.00057 sec


### Lab 1: ndarray 객체를 생성하고 속성을 알아보자

넘파이의 다차원 배열을 이해하기 위해 다음과 같은 일들을 수행

1. 0에서 9까지의 정수 값을 가지는 리스트를 만들자. 이 리스트를 이용하여 넘파이의 ndarray 객체 array_a를 만들고 그 내용을 출력해 보라.

2. range() 함수를 사용하여 0에서 9까지의 정수 값을 가지는 ndarray 객체 array_b를 만들고 아래의 결과와 같이 나타나도록 하여라.

3. 문제 2의 코드를 수정하여 0에서 9까지의 정수 값 중에서 짝수를 가지는 ndarray 객체 array_c를 생성하여라.

4. array_c의 shape, ndim, dtype, size, itemsize를 출력해보라.

In [17]:
array_a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f'실습 1: array_a = {array_a}')

array_b = np.array(range(10))
print(f'실습 2: array_b = {array_b}')

array_c = np.array(range(0, 10, 2))
print(f'실습 3 : array_c = {array_c}')

print('실습 4: ')
print(f'array_c의 shape : {array_c.shape}')
print(f'array_c의 ndim : {array_c.ndim}')
print(f'array_c의 dtype : {array_c.dtype}')
print(f'array_c의 size : {array_c.size}')
print(f'array_c의 itemsize : {array_c.itemsize}')

실습 1: array_a = [0 1 2 3 4 5 6 7 8 9]
실습 2: array_b = [0 1 2 3 4 5 6 7 8 9]
실습 3 : array_c = [0 2 4 6 8]
실습 4: 
array_c의 shape : (5,)
array_c의 ndim : 1
array_c의 dtype : int64
array_c의 size : 5
array_c의 itemsize : 8


### Lab 2: 여러 사람의 BMI를 빠르고 간편하게 계산하기

In [9]:
heights = [1.83, 1.76, 1.69, 1.86, 1.77, 1.73]
weights = [86, 74, 59, 95, 80, 68]

np_heights = np.array(heights)
np_weights = np.array(weights)

bmi = np_weights / (np_heights ** 2)

print(f'대상자들의 키: {np_heights}')
print(f'대상자들의 몸무게: {np_weights}')
print(f'대상자들의 BMI')

print(bmi)
print(bmi[bmi > 25])

대상자들의 키: [1.83 1.76 1.69 1.86 1.77 1.73]
대상자들의 몸무게: [86 74 59 95 80 68]
대상자들의 BMI
[25.68007405 23.88946281 20.65754    27.45982194 25.53544639 22.72043837]
[25.68007405 27.45982194 25.53544639]


In [20]:
scores = np.array([88, 72, 93, 94, 89, 78, 99])
print(scores[2])
print(scores[-1])
print(scores[0:3])
print(scores[1:4])
print(scores[:3])
print(scores[3:])
print(scores[4:-1])

93
99
[88 72 93]
[72 93 94]
[88 72 93]
[94 89 78 99]
[89 78]


In [23]:
ages = np.array([18, 19, 25, 30, 28])

y = ages > 20
print(y)

ages[ages > 20]

[False False  True  True  True]


array([25, 30, 28])

In [27]:
score = np.array([69, 34, 55, 79, 90, 57, 92, 59, 69, 77])
score[score >= 60]

array([69, 79, 90, 92, 69, 77])

In [11]:
y = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(y)

np_array = np.array(y)
print(np_array)

print(np_array[0][1])
print(np_array[2][2])

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
9


In [34]:
np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np_array[0, 2])
print(np_array[0, 0])
print(np_array[2, -1])

np_array[0, 0] = 12
print(np_array)

np_array[2, 2] = 1.234
print(np_array)

3
1
9
[[12  2  3]
 [ 4  5  6]
 [ 7  8  9]]
[[12  2  3]
 [ 4  5  6]
 [ 7  8  1]]


In [39]:
np_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(np_array)

print(np_array[0:2, 2:4])
print(np_array[0])
print(np_array[1, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[3 4]
 [7 8]]
[1 2 3 4]
[6 7]


In [1]:
import numpy as np

np_array = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12],
                     [13, 14, 15, 16]])

print(np_array[::2][::2])
print(np_array[::2, ::2])

[[1 2 3 4]]
[[ 1  3]
 [ 9 11]]


In [45]:
np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(np_array > 5)
print(np_array[np_array > 5])

print(np_array[:, 2])
print(np_array[:, 2] > 5)

print(np_array % 2 == 0)
print(np_array[np_array % 2 == 0])

[[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]
[3 6 9]
[False  True  True]
[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]


### Lab 3: 2차원 배열 연습하기

In [ ]:
x = np.array([['a', 'b', 'c', 'd'],
              ['c', 'c', 'g', 'h']])

mat_a = np.array([[10, 20, 30], [10, 20, 30]])
mat_b = np.array([[2, 2, 2], [1, 2, 3]])

print(x[x == 'c'])      # 'c' 원소만 있는 부분을 추출함
print(mat_a - mat_b)    # 배열 mat_a의 모든 원소에서 mat_b의 모든 원소를 뺀다

['c' 'c' 'c']
[[ 8 18 28]
 [ 9 18 27]]


### Lab 4: 넘파이 배열의 형태 알아내고 슬라이싱하여 연산

In [48]:
x = np.array([[1.83, 1.76, 1.69, 1.86, 1.77, 1.73],
              [86.0, 74.0, 59.0, 95.0, 80.0, 68.0]])
y = x[0:2, 1:3]
z = x[0:2][1:3]

print(f'x shpae: {x.shape}')
print(f'y shape: {y.shape}')
print(f'z shape: {z.shape}')
print(f'z values = : {z}')

bmi = x[1] / (x[0] ** 2)
print('BMI data')
print(bmi)

x shpae: (2, 6)
y shape: (2, 2)
z shape: (1, 6)
z values = : [[86. 74. 59. 95. 80. 68.]]
BMI data
[25.68007405 23.88946281 20.65754    27.45982194 25.53544639 22.72043837]


In [49]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [51]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [52]:
print(np.arange(1, 10, 2))
print(np.arange(1, 10, 2.5))

[1 3 5 7 9]
[1.  3.5 6.  8.5]


In [54]:
print(range(5))
print(list(range(5)))
print(np.array(range(5)))

range(0, 5)
[0, 1, 2, 3, 4]
[0 1 2 3 4]


### Lab 5: 2차원 배열에서 특정 조건을 만족하는 행만 추출하기

In [12]:
players = [[180, 76.4],
           [183, 86.2],
           [181, 78.5],
           [176, 80.1]]

np_players = np.array(players)

print('몸무게가 80 이상인 선수 정보')
print(np_players[np_players[:, 1] >= 80.0])

print('키가 180 이상인 선수 정보')
print(np_players[np_players[:, 0] >= 180.0])

몸무게가 80 이상인 선수 정보
[[183.   86.2]
 [176.   80.1]]
키가 180 이상인 선수 정보
[[180.   76.4]
 [183.   86.2]
 [181.   78.5]]


In [56]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [57]:
np.logspace(0, 5, 10)

array([1.00000000e+00, 3.59381366e+00, 1.29154967e+01, 4.64158883e+01,
       1.66810054e+02, 5.99484250e+02, 2.15443469e+03, 7.74263683e+03,
       2.78255940e+04, 1.00000000e+05])

In [58]:
y = np.arange(12)
print(y)

y.reshape(3, 4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
y.reshape(6, -1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [60]:
y.reshape(7, 2)

ValueError: cannot reshape array of size 12 into shape (7,2)

In [61]:
y.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [67]:
np.random.seed(100)
print(np.random.rand(5))
print(np.random.rand(5, 3))
print()

a = 10
b = 20
print((b - a) * np.random.rand(5) + a)
print()

print(np.random.randint(1, 7, size=10))
print(np.random.randint(1, 11, size=(4, 7)))

[0.54340494 0.27836939 0.42451759 0.84477613 0.00471886]
[[0.12156912 0.67074908 0.82585276]
 [0.13670659 0.57509333 0.89132195]
 [0.20920212 0.18532822 0.10837689]
 [0.21969749 0.97862378 0.81168315]
 [0.17194101 0.81622475 0.27407375]]

[14.31704184 19.4002982  18.17649379 13.3611195  11.75410454]

[4 1 3 2 2 4 3 6 4 1]
[[ 2  1  8  7  3  1  9]
 [ 3  6  2  9  2  6  5]
 [ 3  9  4  6  1 10  4]
 [ 7  4  5  8  7  4 10]]


In [68]:
np.random.randn(5)

array([-1.02933685, -0.51099219, -2.36027053,  0.10359513,  1.73881773])

In [69]:
np.random.randn(5, 4)

array([[ 1.24187584,  0.13241276,  0.57779396, -1.57590571],
       [-1.29279424, -0.65991979, -0.87400478, -0.68955061],
       [-0.53547985,  1.52795302,  0.64720579, -0.67733661],
       [-0.2650188 ,  0.74610644, -3.13078483,  0.05962178],
       [-0.87521111,  1.06487833, -0.57315265, -0.80327849]])

In [70]:
mu = 10
sigma = 2
randoms = mu + sigma + np.random.randn(5, 4)
randoms

array([[13.09297163, 12.65127758, 14.16052479, 11.36086993],
       [11.66631247, 11.56239814, 10.09420512, 10.77098067],
       [12.79489886, 10.83949186, 12.54605552, 13.16325833],
       [12.65887702, 12.52368926, 13.32715607, 13.11252447],
       [10.92537039, 12.34341616, 12.98543754, 12.73650168]])

In [71]:
m = 175
sigma = 10
heights = m + sigma * np.random.randn(10000)
heights

array([154.19537366, 172.0141403 , 157.70789077, ..., 168.27903126,
       164.92114975, 173.12062171])

In [74]:
print(np.mean(heights))
print(np.median(heights))

174.9972570108985
174.90487455543172


In [76]:
a = np.array([3, 7, 1, 2, 21])
print(np.mean(a))
print(np.median(a))

6.8
3.0


### Lab 6: 배열의 형태를 바꾸어 보자

In [81]:
a = np.arange(1, 37)
print(f'a :\n{a}')

b = a.reshape(3, 12)
print(f'b :\n{b}')

c = a.reshape(4, 9)
print(f'c :\n{c}')

d = a.reshape(3, 2, 6)
print(f'd :\n{d}')

a :
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
b :
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32 33 34 35 36]]
c :
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]]
d :
[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]]]


### Lab 7: 평균과 중앙값 계산 연습

In [82]:
players = np.zeros((100, 3))
players[:, 0] = np.random.randn(100) + 175
players[:, 1] = np.random.randn(100) + 70
players[:, 2] = np.floor(10 * np.random.randn(100)) + 22

heights = players[:, 0]
print(f'신장 평균값: {np.mean(heights)}')
print(f'신장 중앙값: {np.median(heights)}')

weights = players[:, 1]
print(f'체중 평균값: {np.mean(weights)}')
print(f'체중 중앙값: {np.median(weights)}')

ages = players[:, 2]
print(f'나이 평균값: {np.mean(ages)}')
print(f'나이 중앙값: {np.median(ages)}')

신장 평균값: 174.77170127299266
신장 중앙값: 174.64811558260504
체중 평균값: 69.95750927697883
체중 중앙값: 70.05524358619635
나이 평균값: 22.29
나이 중앙값: 23.0


In [23]:
players = np.random.randn(100, 3)
players[:, 0] = 175 + 10 * players[:, 0]
players[:, 1] = 70 + 10 * players[:, 1]
players[:, 2] = np.floor(22 + 10 * players[:, 2])

print(f"신장 평균값: {np.mean(players[:, 0])}")
print(f"체중 평균값: {np.mean(players[:, 1])}")
print(f"나이 평균값: {np.mean(players[:, 2])}")

print(f"신장 중앙값: {np.median(players[:, 0])}")
print(f"체중 중앙값: {np.median(players[:, 1])}")
print(f"나이 중앙값: {np.median(players[:, 2])}")

신장 평균값: 176.57833981596167
체중 평균값: 70.38887263341506
나이 평균값: 22.03
신장 중앙값: 174.7989854668283
체중 중앙값: 70.39785234759987
나이 중앙값: 22.0


In [83]:
x = [i for i in range(100)]
y = [i ** 2 for i in range(100)]

result = np.corrcoef(x, y)
print(result)

[[1.         0.96764439]
 [0.96764439 1.        ]]


In [84]:
x = [i for i in range(100)]
y = [i ** 2 for i in range(100)]
z = [100 * np.sin(3.14*i/100) for i in range(100)]

result = np.corrcoef([x, y, z])
print(result)

[[ 1.          0.96764439  0.03763255]
 [ 0.96764439  1.         -0.21532645]
 [ 0.03763255 -0.21532645  1.        ]]
