# NumPy

In [1]:
import numpy as np

In [2]:
np.random.seed(100)

In [ ]:
players = np.zeros((100, 3))
players[:, 0] = 10 * np.random.randn(100) + 175
players[:, 1] = 10 * np.random.randn(100) + 70
players[:, 2] = np.floor(10 * np.random.randn(100)) + 22

heights = players[:, 0]
weights = players[:, 1]
ages = players[:, 2]

print(f'신장 평균값: {np.mean(heights)}')
print(f'체중 평균값: {np.mean(weights)}')
print(f'나이 평균값: {np.mean(ages)}')

print(f'신장 중앙값: {np.median(heights)}')
print(f'체중 중앙값: {np.median(weights)}')
print(f'나이 중앙값: {np.median(ages)}')

신장 평균값: 174.92376657195143
체중 평균값: 69.82864400475772
나이 평균값: 22.67
신장 중앙값: 174.83783342882006
체중 중앙값: 69.91085728179165
나이 중앙값: 24.0


In [7]:
players = np.random.randn(100, 3)
players[:, 0] = 175 + 10 * players[:, 0]
players[:, 1] = 70 + 10 * players[:, 1]
players[:, 2] = np.floor(22 + 10 * players[:, 2])

print(f"신장 평균값: {np.mean(players[:, 0])}")
print(f"체중 평균값: {np.mean(players[:, 1])}")
print(f"나이 평균값: {np.mean(players[:, 2])}")

print(f"신장 중앙값: {np.median(players[:, 0])}")
print(f"체중 중앙값: {np.median(players[:, 1])}")
print(f"나이 중앙값: {np.median(players[:, 2])}")

신장 평균값: 175.93715105502463
체중 평균값: 68.87610142909654
나이 평균값: 24.26
신장 중앙값: 175.54000091180853
체중 중앙값: 68.13523267931768
나이 중앙값: 24.0


In [13]:
import numpy as np

# 3차원 배열 생성
data = np.arange(1, 37).reshape(3, 4, 3)
print(f"Original 3D Array:\n {data}")

# Fancy 인덱싱
layer_indices = [0, 2]
col_indices = [1, 2]
print(f"\nFancy Indexing Result: \n {data[layer_indices, :, col_indices]}")

Original 3D Array:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]

Fancy Indexing Result: 
 [[ 2  5  8 11]
 [27 30 33 36]]


# Pandas